namespace ExpenseTracker.Enums
{
    /// <summary>
    /// Represents available sources of income for a <see cref="Model.Income"/>.
    /// </summary>
    internal enum IncomeSource
    {
        /// <summary>
        /// Income received as a regular salary.
        /// </summary>
        Salary,

        /// <summary>
        /// One-time or periodic bonus payments.
        /// </summary>
        Bonus,

        /// <summary>
        /// Payment for overtime work.
        /// </summary>
        Overtime,

        /// <summary>
        /// Income from freelance or contract work.
        /// </summary>
        Freelance,

        /// <summary>
        /// Income generated by a business.
        /// </summary>
        Business,

        /// <summary>
        /// Income from renting property.
        /// </summary>
        Rental,

        /// <summary>
        /// Interest earned on savings or investments.
        /// </summary>
        Interest,

        /// <summary>
        /// Dividend payments from investments.
        /// </summary>
        Dividend,

        /// <summary>
        /// Pension or retirement income.
        /// </summary>
        Pension,

        /// <summary>
        /// Monetary gifts received.
        /// </summary>
        Gift,

        /// <summary>
        /// Refunds or reimbursements.
        /// </summary>
        Refund,

        /// <summary>
        /// Any other income source not listed above.
        /// </summary>
        Other,
    }
}